feat: Optimized the activity code
qor5/admin pull request #255
Opened 2024-06-07 03:52 UTC by cubxxw

2024-06-07 04:10 UTC, sunfmin requested changes

2024-06-07 04:10 UTC, sunfmin commented on activity/activity_log.go
> +	Comments string `gorm:"type:text;"`
这个应该是单数 `Comment`，因为一条 ActivityLog 最多就一条 Comment

2024-06-07 04:10 UTC, sunfmin commented on activity/admin.go
> +		listing   = mb.Listing("CreatedAt", "Creator", "Action", "ModelKeys", "ModelLabel", "ModelName", "Timeline")
这个列表页面的主体是 ActivityLog，Listing 的每一行是一条 ActivityLog，而 Timeline 是显示在其他 Model 的详细页面的多条 ActivityLog，所以这里无法在列表里显示 Timeline

2024-06-07 04:10 UTC, sunfmin commented on activity/builder.go
> +type TimelineItem struct {
TimelineItem 的数据基本上是从 ActivityLog 来，多加一个 struct 进行转换意义不是很大。个人意见，非要加也 OK

2024-06-07 04:10 UTC, sunfmin commented on activity/note/config.go
> +func tabsPanel(db *gorm.DB, mb *presets.ModelBuilder) presets.TabComponentFunc {
这些 tab 是以前为了加到 tab 里的，现在这个东西不这样设计了，只为了生成一个 Timeline 放到其他 Model 的详细页面里，所以这些旧代码不要。

2024-06-07 04:16 UTC, sunfmin commented on activity/note/config.go
> +func tabsPanel(db *gorm.DB, mb *presets.ModelBuilder) presets.TabComponentFunc {
还有就是测试要加
- 添加 Note的
- 生成系统 log的
- 显示 Timeline 的
- 删除 Note 的
- 等等其他自己想想

2024-06-07 06:09 UTC, cubxxw commented on activity/activity_log.go
> +	Comments string `gorm:"type:text;"`
细节

2024-06-11 01:49 UTC, sunfmin requested changes

2024-06-11 01:49 UTC, sunfmin commented on activity/.DS_Store
这个文件不要提交上去，加到 gitignore 里

2024-06-11 01:49 UTC, sunfmin commented on activity/builder.go
> +type AfterCreateFunc func(db *gorm.DB) error
https://theplant.slack.com/archives/C02B1UQD1JM/p1716775200467999

2024-06-11 01:49 UTC, sunfmin commented on docs/docs/.gitignore
是不是一个项目只保留一个 gitignore 就够了。

2024-06-11 01:49 UTC, sunfmin commented on docs/docs/.gitignore
在 admin/docs/docsrc/examples/examples_admin 里面添加使用例子，并且添加自动化测试。

2024-06-11 02:05 UTC, cubxxw commented on docs/docs/.gitignore
docs 偏向于自己的模块化的，如果你的存储库包含多个独立项目，那么最好将它们作为子模块引用。
---
在添加中

2024-06-11 10:49 UTC, sunfmin requested changes

2024-06-11 10:49 UTC, sunfmin commented on activity/builder.go
> +func (b *Builder) WrapAfterCreateFunc(w AfterCreateFuncWrapper) *Builder {
Wrap的应该是Create，因为Wrap之后可以在BeforeCreate也做事情，把目前的create变成一个默认实现，然后使用方可以wrap他在create前后端进行定制

2024-06-11 10:49 UTC, sunfmin commented on activity/note.go
> +type UserNote struct {
不是说合成一个表了？又分成两个表了吗？

2024-06-11 10:50 UTC, sunfmin commented on activity/builder.go
> +func (b *Builder) WrapAfterCreateFunc(w AfterCreateFuncWrapper) *Builder {
我们以后的代码里不会加 Before， After怎么怎么样，只会加Wrap，我那个thread写的不清楚吗

2024-06-11 10:55 UTC, sunfmin requested changes

2024-06-11 10:55 UTC, sunfmin commented on docker-compose.yml
> +version: "3.8"
现在都用theplant/testenv来启动测试数据库，参照下其他的TestMain

2024-06-11 10:55 UTC, sunfmin commented on docs/docsrc/examples/examples_admin/activity.go
> -	// @snippet_begin(NewActivitySample)
这些是写文档需要的，文档中提供代码示例用的

2024-06-11 10:55 UTC, sunfmin commented on docs/docsrc/examples/examples_admin/activity_test.go
> +					PageURL("/with-activity-products").
这个测试没有传入createNote的event，能正常跑吗？

2024-06-18 11:48 UTC, sunfmin requested changes

2024-06-18 11:48 UTC, sunfmin commented on activity/log_builder_test.go
> +	record := builder.NewLogModelData().(*ActivityLog)
既然是只有 ActivityLog 了，这个方法没必要了。可以删掉

2024-06-18 11:48 UTC, sunfmin commented on activity/log_builder_test.go
> +	for i, log := range logs {
这个不要循环判断，可以使用 testingutils.PrettyJsonDiff()，他是先转化成 json，然后再比较

2024-06-18 11:48 UTC, sunfmin commented on activity/log_builder_test.go
> +		if log1.ModelDiffs != `[{"Field":"Title","Old":"test1","Now":"test1-1"},{"Field":"Description","Old":"Description1","Now":"Description1-1"}]` {
用 testingutils.PrettyJsonDiff()

2024-06-18 11:48 UTC, sunfmin commented on activity/model_builder.go
> +	editing.AppendTabsPanelFunc(func(obj any, ctx *web.EventContext) (tab h.HTMLComponent, content h.HTMLComponent) {
AppendTabsPanelFunc不要了，因为用 Timeline 代替了。现在的 activity 不显示在 tab 里了。

2024-06-18 11:48 UTC, sunfmin commented on presets/utils.go
> +func ShowMessage(r *web.EventResponse, msg string, color string) error {
这个不要返回 error 了，web.EventResponse是空直接忽略返回吧，一般不会出现他是 nil 的

2024-06-26 01:18 UTC, closed without merging