Feat UI reborn
qor5/admin pull request #454
Opened 2024-08-08 13:49 UTC by danni-cool

2024-08-08 13:58 UTC, danni-cool commented
it seems the test builder didn't throw any useful information.

2024-08-08 23:45 UTC, sunfmin approved these changes

2024-08-08 23:47 UTC, sunfmin requested changes
Test have to pass

2024-08-08 23:50 UTC, sunfmin requested changes

2024-08-08 23:50 UTC, sunfmin commented on presets/presets.go
> +func (b *Builder) SetContainerClass(name string) {
一般我们都不加Set这个词来设置参数，直接用ContainerClass

2024-08-08 23:50 UTC, sunfmin commented on presets/presets.go
> +func (b *Builder) SetContainerClass(name string) {
如果同一个东西需要Get，那用Get这个词，但是Set这个词是省略的

2024-08-12 03:31 UTC, closed without merging

2024-08-12 03:32 UTC, danni-cool commented on presets/presets.go
> +func (b *Builder) SetContainerClass(name string) {
已经根据规范修改，rebase了master有太多非自己修改，重新提pr